### ISSUE TITLE
replace badger v1 with v2

### ISSUE THREAD

**Issue by mvdan** [ipfs/go-ds-badger#101]
BadgerDB v2 has been out for [nearly a year](https://dgraph.io/blog/post/releasing-badger-v2/), and it's overall better in multiple ways and better supported.

It shouldn't be too difficult to switch, either:

> Also, there are no breaking API changes since v1.6.0.

Would a PR be welcome here?

**Comment by aschmahmann** [comment]
@mvdan we have https://github.com/ipfs/go-ds-badger2 for Badger 2. Arguably there was a better go mod way to do this, but it definitely makes releasing patches to the badger1 and badger2 datastores at the same time less error prone.

However, if you'd like to help with some of the plugging in of this into go-ipfs then that would definitely be welcome.
https://github.com/ipfs/go-ipfs/issues/6818
https://github.com/ipfs/go-ipfs/issues/4279

**Comment by mvdan** [comment]
Oh jeez, I'm not sure how I missed that :) Perhaps add a clear notice in the README in this repo? Because if you don't know where to look, it's very easy to miss the newer library, like I did.

I'm interested to hear how two git repositories make maintaining both versions at the same time easier, though. I maintain multiple major versions of modules in a few git repositories and it's generally easy enough to do.

**Comment by aschmahmann** [comment]
> Perhaps add a clear notice in the README in this repo? Because if you don't know where to look, it's very easy to miss the newer library, like I did.

Seems reasonable 😄 

> I'm interested to hear how two git repositories make maintaining both versions at the same time easier, though.

You'd have to ask @Kubuxu, but it looks like there were some concerns mentioned in https://github.com/ipfs/go-ipfs/issues/6818. I can't speak to why he did it that way, but if I were in his shoes I probably would've done the same thing.

go mod has enough complexity and corner cases such that if you were trying to just get this moving then copying the repo is the approach that's guaranteed to just work™.

**Comment by willscott** [comment]
fwiw, both badger and badger2 have been getting [fuzz](https://github.com/ipfs/go-datastore/tree/master/fuzz) test by [oss-fuzz](https://github.com/google/oss-fuzz/blob/master/projects/ipfs/build.sh#L44-L45) for the last several months, which hopefully is starting to increase our confidence in the badger2 implementation.

**Comment by aschmahmann** [comment]
Readme updated #102

**Comment by mvdan** [comment]
If any extra experience counts, I've switched a couple of live projects to v2 earlier this year, and so far zero issues.
