### ISSUE TITLE
Export  `type datastore` 

### ISSUE THREAD

**Issue by robotamer** [ipfs/go-ds-badger#20]
It would be helpful if you could export `type datastore`

**Comment by Stebalien** [comment]
Through a type alias?

**Comment by Stebalien** [comment]
Ah. I see what you're talking about. Yes, we should.

We usually use it through the `Datastore` interface defined in `github.com/ipfs/go-datastore` but yeah, there's no reason we can't export the type here as well. Mind submitting a PR?

**Comment by Stebalien** [comment]
Thanks!
