### ISSUE TITLE
GC Test hang

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ds-badger#24]
Log: [/ipfs/QmVEkbwNQSLcCEJWhxkuUsoA8cdwZjnp79pGNK49MTnZo8](https://ipfs.io/ipfs/QmVEkbwNQSLcCEJWhxkuUsoA8cdwZjnp79pGNK49MTnZo8)

(edit: fix link)

**Comment by schomatis** [comment]
I'll take a look at it, did we end up updating the purge call?

**Comment by schomatis** [comment]
Oh, not yet: https://github.com/ipfs/go-ds-badger/pull/22.

**Comment by Stebalien** [comment]
Merged. Was that the issue?

**Comment by schomatis** [comment]
> Was that the issue?

I don't know, sorry, I was just thinking out loud what had been the latest modifications to Badgers' GC.

**Comment by schomatis** [comment]
So, `TestGC` is a very expensive test as it uses a separate transaction for each of the 10K put/delete operations, and it does take 3-4 minutes to complete (in my local, below average, PC). This is clearly below the 10 minute threshold but was it possible that the server was a bit overloaded and this took longer than usual? The stack trace shows that a write operation was talking place,

```
goroutine 10468 [syscall]:
syscall.Syscall(0x1, 0x7, 0xc00a9db980, 0x52, 0xe80630, 0xc00a9f1a08, 0x464d8c)
	/home/travis/.gimme/versions/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.write(0x7, 0xc00a9db980, 0x52, 0x1980, 0x77, 0x454601, 0x0)
	/home/travis/.gimme/versions/go/src/syscall/zsyscall_linux_amd64.go:1005 +0x68
syscall.Write(0x7, 0xc00a9db980, 0x52, 0x1980, 0xc0000aa5d0, 0x40, 0x63)
	/home/travis/.gimme/versions/go/src/syscall/syscall_unix.go:191 +0x6b
internal/poll.(*FD).Write(0xc000098190, 0xc00a9db980, 0x52, 0x1980, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go/src/internal/poll/fd_unix.go:267 +0x1d0
os.(*File).write(0xc00000e020, 0xc00a9db980, 0x52, 0x1980, 0x8bb2792717, 0xe62b80, 0x5a74d)
	/home/travis/.gimme/versions/go/src/os/file_unix.go:265 +0x70
os.(*File).Write(0xc00000e020, 0xc00a9db980, 0x52, 0x1980, 0x2, 0x2, 0x4)
	/home/travis/.gimme/versions/go/src/os/file.go:145 +0x8e
gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger.(*valueLog).write.func1(0xc00a9d8288, 0x3dd4984)
	/home/travis/gopath/src/gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger/value.go:762 +0x38b
gx/ipfs/QmeAEa8FDWAmZJTL6YcM1oEndZ4MyhCr5rTsjYZQui1x1L/badger.(*valueLog).write(0xc00a9d8138, 0xc00ad84aa0, 0x1, 0xa, 0x0, 0x0)
[...]
```

@Stebalien Can this failed test be replicated?

**Comment by Stebalien** [comment]
I haven't replicated it. I just noticed it once. Sounds like we should consider batching.

**Comment by Stebalien** [comment]
On my machine, it took less than a second to complete but we might as well merge that PR and see where this goes.

**Comment by schomatis** [comment]
Yes, the same on mine, but the online test that now took 8 seconds was taking more than 30 and with *a lot* of variability,

* https://travis-ci.org/ipfs/go-ds-badger/builds/396227640#L523

* https://travis-ci.org/ipfs/go-ds-badger/builds/396225773#L526

* https://travis-ci.org/ipfs/go-ds-badger/builds/391001834#L523

**Comment by Stebalien** [comment]
Hm. But *minutes* feels like a deadlock (possibly one that only shows up on travis). We'll see.

**Comment by schomatis** [comment]
> But minutes feels like a deadlock

Yes, it has been known to happen, https://github.com/dgraph-io/badger/issues/410.
