### ISSUE TITLE
Periodically garbage collect

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ds-badger#51]
We should periodically garbage collect in case the user has garbage collection turned off. Otherwise, we'll never delete _anything_.

**Comment by raulk** [comment]
Why is `gcDiscardRatio` statically configured to 0.1? The struct field is unexported :-(

**Comment by Stebalien** [comment]
Not exporting it was probably a mistake, @magik6k?

**Comment by raulk** [comment]
Gotcha, I'll submit a PR. Another thing, overriding the error here creates ambiguity: https://github.com/ipfs/go-ds-badger/blob/master/datastore.go#L286. Badger returns nil if one file was collected, and callers may use this as a hint to continue collecting by calling GC again. Overriding the "nothing was collected" error to nil makes it impossible to discriminate whether it's worth calling GC again or not :-(

**Comment by Stebalien** [comment]
> If we want to decouple this from badger implementation-specific errors, we can return a second value to signal if something was collected, or not, or we don't know (some stores may not expose this event).

That's the issue. However, for every datastore _except_ badger, re-running GC till it removes nothing is just a waste of time so I'm not sure how useful that is.

See https://github.com/ipfs/go-ds-badger/pull/56 that just does this automatically.

**Comment by magik6k** [comment]
> Not exporting it was probably a mistake, @magik6k?

Yeah, I probably meant to export it, but also set some value that would mostly work to quickly test and never changed it

**Comment by aarshkshah1992** [comment]
@Stebalien Is this up for grabs ?

**Comment by Stebalien** [comment]
Yes! (it's also pretty easy to review so it should get merged pretty quickly).

**Comment by Stebalien** [comment]
Fixed in #72.
