### ISSUE TITLE
Please do not depend on v2.0.0-rc2

### ISSUE THREAD

**Issue by campoy** [ipfs/go-ds-badger#64]
Hi there,

I'm maintaining Badger and as part of our v2 release process, we realized that ipfs was depending on an unexpected tag.

It seems that the version you should be depending on is `v1.5.5` which brings support for Go Modules and is backwards compatible with the code pointed by `v2.0.0-rc.2`. That tag was the remains of a failed release sometime last year and should have never been pushed, as I explain in issue https://github.com/dgraph-io/badger/issues/904.

Thanks for understanding and sorry for the inconveniences.

**Comment by Kubuxu** [comment]
We are removing dependency on this tag in: https://github.com/ipfs/go-ds-badger/pull/62

**Comment by campoy** [comment]
Fixed with #65
