### ISSUE TITLE
badger version doesn't build under 32-bit platforms

### ISSUE THREAD

**Issue by ivilata** [ipfs/go-ds-badger#9]
While building IPFS (which uses go-ds-badger 0.4.1) on an i686 (32-bit) Debian Squeeze machine, I came across the following error:

```
[done] [install] go-ds-badger             QmUamAGkvPp1w84dfc2YMy9ic6iyBvaRoaTiaat8Crtawq 0s
[done] [install] go-testutil              QmQgLZP9haZheimMHqqAjJh2LhRmNfEoZDfbtkpeMhi9xK 0s
# gx/ipfs/QmTBxwy8cerzXbZQFUwTBCSxx55jUgVzudFcpmnAHUGuPy/badger
../../../gx/ipfs/QmTBxwy8cerzXbZQFUwTBCSxx55jUgVzudFcpmnAHUGuPy/badger/kv.go:86:6: constant 1099511627776 overflows int
```

Around these lines there are a couple appearances of ``maxKeySize<<20``.  Just wrapping ``maxKeySize`` in ``int64()`` seems to avoid the error.

I can no longer see such lines (or file) in dgraph-io/badger, so the issue may have been fixed there, so probably go-ds-badger should depend on a newer version of badger to avoid this issue.

Sorry if this isn't the right place to report this, I'm not very used to Go/gx packaging.  Thanks!

**Comment by Kubuxu** [comment]
Can you try building https://github.com/dgraph-io/badger on those platforms and if the bug still exists report it there? Otherwise we will propagate the package.

**Comment by ivilata** [comment]
I used karalabe/xgo to build ``linux/arm-6`` and ``linux/386`` from a Debian Sid ``amd64`` host (Go 1.9.1), like this:

```
mkdir /tmp/BADGER
export GOPATH=/tmp/BADGER
cd $GOPATH
export PATH=$GOPATH/bin:$HOME/env/go/xgo/bin:$PATH
go get -d github.com/dgraph-io/badger
cd src/github.com/dgraph-io/badger/
xgo --targets=linux/386 ./cmd/badger_info
xgo --targets=linux/arm-6 ./cmd/badger_info
```

And it succeeded to build.  I created a Debian Stretch ``i386`` host and ``go get github.com/dgraph-io/badger`` succeeded (but only after upgrading Go 1.7.4 to Go 1.8.1).  So it looks like Badger's ``HEAD`` doesn't have this issue.

**However**, if I use ``go get -d github.com/dgraph-io/badger``, then check out tag ``v0.8`` (which does have the offending lines), then run ``go build``, it fails with:

```
# github.com/dgraph-io/badger
./kv.go:86: constant 1099511627776 overflows int
```

So the error does seem to be related with that particular version of Badger.

I'd like to know, if you propagate a newer version of the package, how/when would it hit IPFS's ``master``?

Please indicate if you need additional info from my side, thanks!

**Comment by ivilata** [comment]
> I'd like to know, if you propagate a newer version of the package, how/when would it hit IPFS's ``master``?

Well, I guess that as soon as you published a fixed version of ``go-ds-badger`` to ``gx``, one could be able to temporarily patch IPFS locally to use it.`:)`

**Comment by magik6k** [comment]
Should be fixed with https://github.com/ipfs/go-ds-badger/pull/10

**Comment by ivilata** [comment]
The 32-bit IPFS build succeeded now, thanks!
